#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no-install pretty-quick --staged && npx lint-staged
# # Disable concurent to run `check-types` after ESLint in lint-staged
# npx lint-staged --concurrent false